# python -m torch.distributed.launch --nproc_per_node=1 --master_port=$RANDOM main.py -a conv6 --dataname cifar10 --config cifar10_conv6_train
# ===== Configuration ===== #
config: cifar10_conv6_train
# ===== Architecture ===== #
arch: 'conv6'
pretrained: False
# ===== Dataset ===== #
dataname: 'cifar10'
datapath: './data/cifar10/'
workers: 20
batch_size: 60
# ===== Initialization ===== #
init_policy: 'kaimingn'
init_kaiming_mode: 'fan_in'
init_kaiming_nonlinearity: 'relu'
init_bias: 'zero'
# ===== Optimization ======== #
optimizer: 'Adam'
epochs: 1
label_smoothing: 0.0
weight_decay: 0.0
lr: 0.0003
lr_policy: 'constant_lr'
warmup_length: 0
lr_step: 0
lr_gamma: 0.0
momentum: 0.0
nesterov: False
evaluate: False
# ===== Pruning ======== #
prepruned_model: False
pruning_strategy: 'lottery'
percent: 0
initial_stage: 0
stages: 5
local_prune: False
prune_bias: False
prune_bn: False
local_quant: False
# ===== Distributed processing ======== #
gpu_idx: '0'
local_rank: 0 
channels_last: False
# ===== Logging ======== #
print_freq_tr: 10
print_freq_ts: 10