# python -m torch.distributed.launch --nproc_per_node=1 --master_port=$RANDOM main.py -a vgg11 --dataname cifar10 --config cifar10_vgg11_quantized
# ===== Configuration ===== #
config: cifar10_vgg11_quantized
# ===== Architecture ===== #
arch: 'vgg11'
pretrained: False
resume: ''
# ===== Dataset ===== #
dataname: 'cifar10'
datapath: './data/cifar10/'
workers: 20
batch_size: 128
# ===== Initialization ===== #
init_policy: 'kaimingn'
init_kaiming_mode: 'fan_in'
init_kaiming_nonlinearity: 'relu'
init_bias: 'zero'
# ===== Optimization ======== #
optimizer: 'SGD+M'
epochs: 1
label_smoothing: 0.0
weight_decay: 0.0001
lr: 0.05
lr_policy: 'cosine_lr'
warmup_length: 0
lr_steps: [80, 120]
lr_gamma: 0.1
lowest_lr: 0.0
scale_coslr: 1.3
exp_coslr: 1
normal_exp_scale: 1500
momentum: 0.9
nesterov: False
evaluate: False
# ===== Pruning ======== #
prepruned_model: True
prepruned_scen: ''
nonpruned_percent: 0.7
quantize_stage: 159
pruning_strategy: 'quantize'
quantize-prepruned: False
quantize-bias: True
prune_bias: False
prune_bn: False
local_quant: False
initial_stage: 0
stages: 160
# ===== Asni ======== #
asni_sin_scale: 16
asni_sin_exponent: 1
asni_sin_mag: 100
asni_perc_max: 100
# ===== Lottery ======== #
percent: 0
local_prune: False
# ===== STR ======== #
init_threshold: -10
init_threshold_type: 'constant'
str-nonlinear: 'sigmoid'
str-activation: 'relu'
# ===== RigL ======== #
# ===== SNIP ======== #
# ===== Distributed processing ======== #
gpu_idx: '7'
local_rank: 0 
channels_last: False
# ===== Logging ======== #
print_freq_tr: 10
print_freq_ts: 10
logterminal: False