# python -m torch.distributed.launch --nproc_per_node=1 --master_port=$RANDOM main.py -a vgg19 --dataname cifar10 --config cifar10_vgg19_train --logterminal
# ===== Configuration ===== #
config: cifar10_vgg19_train
# ===== Architecture ===== #
arch: 'vgg19'
pretrained: False
resume: ''
# ===== Dataset ===== #
dataname: 'cifar10'
datapath: './data/cifar10/'
workers: 20
batch_size: 128
# ===== Initialization ===== #
init_policy: 'kaimingn'
init_kaiming_mode: 'fan_in'
init_kaiming_nonlinearity: 'relu'
init_bias: 'zero'
# ===== Optimization ======== #
optimizer: 'SGD+M'
epochs: 1
label_smoothing: 0.0
weight_decay: 0.0005
lr: 0.05
lr_policy: 'cosine_lr'
warmup_length: 0
lr_steps: [80, 120]
lr_gamma: 0.1
lowest_lr: 0.0
scale_coslr: 1.02
exp_coslr: 1
normal_exp_scale: 1500
momentum: 0.9
nesterov: False
evaluate: False
# ===== Distributed processing ======== #
gpu_ids: '0'
local_rank: 0 
channels_last: False
# ===== Logging ======== #
print_freq_tr: 10
print_freq_ts: 10
logterminal: False