# python -m torch.distributed.launch --nproc_per_node=4 --master_port=$RANDOM main.py -a resnet18 --dataname imagenet --config resnet18_imagenet_str
# ===== Configuration ===== #
config: resnet18_imagenet_str
# ===== Architecture ===== #
arch: 'resnet18'
pretrained: False
resume: ''
# ===== Dataset ===== #
dataname: 'imagenet'
datapath: '/datasets/imagenet/'
workers: 20
batch_size: 200
# ===== Optimization ======== #
optimizer: 'SGD+M'
epochs: 1
label_smoothing: 0.1
weight_decay: 0.0
lr: 0.256
lr_policy: 'normal_lr'
warmup_length: 0
lr_step: 0
lr_gamma: 0.0
lowest_lr: 0.0001
scale_coslr: 1
exp_coslr: 3
normal_exp_scale: 1500
momentum: 0.9
nesterov: False
evaluate: False
# ===== Pruning ======== #
prepruned_model: False
pruning_strategy: 'str'
# ===== Asni ======== #
asni_sin_scale: 6.5
asni_sin_exponent: 3
asni_sin_mag: 80
asni_perc_max: 80
# ===== Lottery ======== #
percent: 0
local_prune: False
# ===== STR ======== #
init_threshold: -10
init_threshold_type: 'constant'
str-nonlinear: 'sigmoid'
str-activation: 'relu'
# ===== RigL ======== #
# ===== SNIP ======== #
initial_stage: 0
stages: 100
prune_bias: False
prune_bn: False
local_quant: False
# ===== Distributed processing ======== #
gpu_idx: '4567'
local_rank: 0 
channels_last: False
# ===== Logging ======== #
print_freq_tr: 10
print_freq_ts: 10