# python -m torch.distributed.launch --nproc_per_node=1 --master_port=$RANDOM main.py -a conv4 --dataname cifar10 --config cifar10_conv4_asni
# ===== Configuration ===== #
config: cifar10_conv4_asni
# ===== Architecture ===== #
arch: 'conv4'
pretrained: False
resume: ''
# ===== Dataset ===== #
dataname: 'cifar10'
datapath: './data/cifar10/'
workers: 20
batch_size: 60
# ===== Initialization ===== #
init_policy: 'kaimingn'
init_kaiming_mode: 'fan_in'
init_kaiming_nonlinearity: 'relu'
init_bias: 'zero'
# ===== Optimization ======== #
optimizer: 'Adam'
epochs: 1
label_smoothing: 0.0
weight_decay: 0.0
lr: 0.0003
lr_policy: 'constant_lr'
warmup_length: 0
lr_step: 0
lr_gamma: 0.0
lowest_lr: 0.001
scale_coslr: 1
exp_coslr: 1
normal_exp_scale: 1500
momentum: 0.9
nesterov: False
evaluate: False
# ===== Pruning ======== #
prepruned_model: False
prepruned_scen: ''
nonpruned_percent: 0
pruning_strategy: 'asni'
# ===== Asni ======== #
asni_sin_scale: 12
asni_sin_exponent: 1
asni_sin_mag: 100
asni_perc_max: 100
# ===== Lottery ======== #
percent: 0
local_prune: False
# ===== STR ======== #
init_threshold: -10
init_threshold_type: 'constant'
str-nonlinear: 'sigmoid'
str-activation: 'relu'
# ===== RigL ======== #
# ===== SNIP ======== #
initial_stage: 0
stages: 25
prune_bias: False
prune_bn: False
local_quant: False
# ===== Distributed processing ======== #
gpu_idx: '0'
local_rank: 0 
channels_last: False
# ===== Logging ======== #
print_freq_tr: 10
print_freq_ts: 10