# python -m torch.distributed.launch --nproc_per_node=1 --master_port=$RANDOM main.py -a fc --dataname mnist --config mnist_fc_str
# ===== Configuration ===== #
config: mnist_fc_str
# ===== Architecture ===== #
arch: 'fc'
pretrained: False
resume: ''
# ===== Dataset ===== #
dataname: 'mnist'
datapath: './data/mnist/'
workers: 20
batch_size: 512
# ===== Initialization ===== #
init_policy: 'kaimingn'
init_kaiming_mode: 'fan_in'
init_kaiming_nonlinearity: 'relu'
init_bias: 'zero'
# ===== Optimization ======== #
optimizer: 'SGD+M'
epochs: 1
label_smoothing: 0.0
weight_decay: 0.0001
lr: 0.256
lr_policy: 'cosine_lr'
warmup_length: 0
lr_step: 0
lr_gamma: 0.0
lowest_lr: 0.01
scale_coslr: 1
exp_coslr: 1
normal_exp_scale: 1500
momentum: 0.9
nesterov: False
evaluate: False
# ===== Pruning ======== #
prepruned_model: False
prepruned_scen: ''
nonpruned_percent: 99.2
pruning_strategy: 'str'
# ===== Asni ======== #
asni_sin_scale: 15
asni_sin_exponent: 1
asni_sin_mag: 100
asni_perc_max: 100
# ===== Lottery ======== #
percent: 0
local_prune: False
# ===== STR ======== #
init_threshold: -4
init_threshold_type: 'constant'
str-nonlinear: 'sigmoid'
str-activation: 'relu'
# ===== RigL ======== #
# ===== SNIP ======== #
initial_stage: 0
stages: 10
prune_bias: False
prune_bn: False
local_quant: False
# ===== Distributed processing ======== #
gpu_idx: '0'
local_rank: 0 
channels_last: False
# ===== Logging ======== #
print_freq_tr: 10
print_freq_ts: 10