# python -m torch.distributed.launch --nproc_per_node=1 --master_port=$RANDOM main.py --config mnist_fc_lottery
# ===== Configuration ===== #
config: mnist_fc_lottery
# ===== Architecture ===== #
arch: 'fc'
pretrained: False
resume: ''
# ===== Dataset ===== #
dataname: 'mnist'
datapath: './data/mnist/'
workers: 20
batch_size: 512
# ===== Optimization ======== #
optimizer: 'SGD+M'
epochs: 1
label_smoothing: 0.0
weight_decay: 0.0
lr: 0.256
lr_policy: 'cosine_lr'
warmup_length: 0
lr_step: 0
lr_gamma: 0.0
lowest_lr: 0.0001
scale_coslr: 1
exp_coslr: 3
normal_exp_scale: 1500
momentum: 0.9
nesterov: False
evaluate: False
# ===== Pruning ======== #
prepruned_model: False
prepruned_scen: '' 
pruning_strategy: 'lottery'
# ===== Asni ======== #
asni_sin_scale: 6.5
asni_sin_exponent: 3
asni_sin_mag: 80
asni_perc_max: 80
# ===== Lottery ======== #
percent: 10
local_prune: False
# ===== STR ======== #
init_threshold: -10
init_threshold_type: 'constant'
str-nonlinear: 'sigmoid'
str-activation: 'relu'
# ===== RigL ======== #
# ===== SNIP ======== #
initial_stage: 0
stages: 3
prune_bias: False
prune_bn: False
local_quant: False
# ===== Distributed processing ======== #
gpu_idx: '01'
local_rank: 0 
channels_last: False
# ===== Logging ======== #
print_freq_tr: 10
print_freq_ts: 10