# python -m torch.distributed.launch --nproc_per_node=1 --master_port=$RANDOM main.py --config mnist_fc_str
# ===== Configuration ===== #
config: mnist_fc_str
# ===== Architecture ===== #
arch: 'fc'
pretrained: False
resume: ''
# ===== Dataset ===== #
dataname: 'mnist'
datapath: './data/mnist/'
workers: 20
batch_size: 512
# ===== Optimization ======== #
optimizer: 'SGD+M'
epochs: 1
label_smoothing: 0.0
weight_decay: 0.012
lr: 0.256
lr_policy: 'cosine_lr'
warmup_length: 0
lr_step: 0
lr_gamma: 0.0
momentum: 0.0
nesterov: False
evaluate: False
# ===== Pruning ======== #
prepruned_model: False
pruning_strategy: 'str'
# ===== Lottery ======== #
percent: 10
local_prune: False
# ===== STR ======== #
init_threshold: -10
init_threshold_type: 'constant'
str_nonlinear: 'sigmoid'
str_activation: 'relu'
# ===== RigL ======== #
# ===== SNIP ======== #
initial_stage: 0
stages: 10
prune_bias: False
prune_bn: False
local_quant: False
# ===== Distributed processing ======== #
gpu_idx: None
local_rank: 0 
channels_last: False
# ===== Logging ======== #
print_freq_tr: 10
print_freq_ts: 10