# python -m torch.distributed.launch --nproc_per_node=1 --master_port=$RANDOM main.py -a conv4a --dataname fashionmnist --config fashionmnist_conv4a_train --logterminal
# ===== Configuration ===== #
config: fashionmnist_conv4a_train
# ===== Architecture ===== #
arch: 'conv4a'
pretrained: False
# ===== Dataset ===== #
dataname: 'mnist'
datapath: './data/fashionmnist/'
workers: 20
batch_size: 512
# ===== Initialization ===== #
init_policy: 'kaimingn'
init_kaiming_mode: 'fan_in'
init_kaiming_nonlinearity: 'relu'
init_bias: 'zero'
# ===== Optimization ======== #
optimizer: 'SGD+M'
epochs: 1
label_smoothing: 0.0
weight_decay: 0.0
lr: 0.032
lr_policy: 'cosine_lr'
warmup_length: 0
lr_step: 0
lr_gamma: 0.0
momentum: 0.0
nesterov: False
evaluate: False
# ===== Distributed processing ======== #
gpu_ids: '0'
local_rank: 0 
channels_last: False
# ===== Logging ======== #
print_freq_tr: 10
print_freq_ts: 10
logterminal: False